title: seavaske.com | Personal page of Charles Vaske
description: Personal page of Charles Vaske, computational biology, bioinformatics, cancer genomics, clinical diagnostics, and molecular discovery
url: "https://www.seavaske.com"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - paradigm-method.key
